#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [30]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [36]:
a = np.zeros(10) #10 is the size 
print(a)
#vector is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [126]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [33]:
a = np.arange(10,50)
print(a)
#arange is to order

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [127]:
a = np.arange(0,9).reshape(3,3) #3x3 is 3 rows and 3 numbers in the list
print(a)
# matrix:[[0 1 2], [3 4 5], [6 7 8]]
#reshape is to reshape a vector into matrix

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [14]:
a = np.nonzero([1,2,0,0,4,0])
print(a)
#nonzero returns the indices of the elements that are non-zero.

(array([0, 1, 4]),)


#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [15]:
a = np.eye(3)
print(a)
#eye returns a matrix with 1 on the diagonal and 0 elsewhere.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [175]:
a = np.random.random((3,3,3)) #the third 3 means that there are 3 lists in the lists 
print(a)
#array: matrix, vector
#random.random returns random floats in the interval of 0 and 1.

[[[0.49110101 0.83003102 0.30958567]
  [0.14262465 0.19414441 0.7936128 ]
  [0.45166233 0.01598435 0.7114743 ]]

 [[0.20342276 0.34564135 0.3695254 ]
  [0.09264654 0.39902133 0.59014216]
  [0.70115867 0.7902818  0.26524713]]

 [[0.81353576 0.48657389 0.56808707]
  [0.96119661 0.9712674  0.91791182]
  [0.17804697 0.22988741 0.58538857]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [ ]:
a = np.random.random((10,10)) 
print(a)

In [132]:
a = np.random.random((10,10)) 
print(a)

[[0.03282012 0.58392442 0.87074643 0.04588728 0.65969731 0.87105342
  0.61369101 0.1112203  0.81131632 0.84090483]
 [0.63576596 0.39711524 0.77555839 0.98975542 0.24648865 0.24657607
  0.92868299 0.11899035 0.04246907 0.55508096]
 [0.42504746 0.17570448 0.09626315 0.38414016 0.84579616 0.11119524
  0.85380738 0.36886054 0.98426302 0.54298335]
 [0.6673892  0.72943911 0.85925704 0.32707127 0.3421388  0.97406179
  0.10916289 0.86449143 0.64856692 0.28287214]
 [0.35279097 0.83823622 0.44123338 0.91661803 0.51319617 0.02890198
  0.24150983 0.22219598 0.40135112 0.70149073]
 [0.52600045 0.82229198 0.64454221 0.10192971 0.38435209 0.92041218
  0.724575   0.82354471 0.76160581 0.10133708]
 [0.98041199 0.71887845 0.61526396 0.13014785 0.87071783 0.54100515
  0.49296413 0.0416488  0.90846799 0.09053733]
 [0.83082705 0.25324022 0.4465266  0.44705735 0.93692756 0.65880155
  0.44035457 0.89583341 0.72979628 0.3461923 ]
 [0.22654855 0.33587456 0.16576422 0.46904471 0.58323496 0.61608224
  0.07614691

In [131]:
print(a.min())
print(a.max())

0
2


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [135]:
a = np.random.random(30)
print(a)
print(a.mean())

[0.10413085 0.54787838 0.67822386 0.33884774 0.66472277 0.41813975
 0.57444248 0.04636661 0.44894415 0.41850273 0.17852196 0.7964227
 0.4596593  0.5566106  0.76757631 0.87489616 0.77487764 0.57265359
 0.70726203 0.64558729 0.33548672 0.28555439 0.85914225 0.89707199
 0.70202121 0.64368781 0.410468   0.15444862 0.04480883 0.30670397]
0.5071220237680649


#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [136]:
a = np.diag(np.arange(1, 5),k=-1) 
print(a)
#diag is used to construct a diagonal array 
#k is the position in the diagonal, row -1 (0=0, -1=1, -2=0...)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [138]:
a = np.random.random((5,5))
print(a)
normalize = (a - np.mean (a)) / (np.std (a))
print(normalize)
#normalize is to find (x -mean)/std

[[4.44194910e-01 7.36055658e-01 7.57587625e-02 9.90233709e-01
  7.28520349e-01]
 [4.43854968e-01 7.14725441e-01 8.88029854e-01 4.69799751e-01
  5.54697256e-01]
 [7.07541978e-01 7.05915180e-01 6.57964316e-01 9.57275499e-01
  5.16474701e-01]
 [3.20834588e-01 8.73510995e-01 5.24790190e-01 3.02177901e-01
  5.48330523e-01]
 [4.90972163e-01 7.13200711e-04 6.12795942e-01 8.08820921e-01
  4.69542911e-01]]
[[-0.56918231  0.63857032 -2.09381256  1.69038771  0.60738837]
 [-0.57058903  0.55030348  1.26745665 -0.46322659 -0.11191116]
 [ 0.5205775   0.51384563  0.31541956  1.55400293 -0.2700804 ]
 [-1.07966121  1.20737598 -0.23566997 -1.15686468 -0.13825742]
 [-0.37561277 -2.40435954  0.12850774  0.93968117 -0.46428943]]


#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [178]:
a = np.random.randint(0,10,15) #from 1 to 11 and return 10 values
print(a)
b = np.random.randint(0,10,15)
print(b)
print(np.intersect1d(a,b))

[8 8 5 7 0 3 4 1 6 5 9 4 4 1 0]
[9 9 1 9 1 7 0 8 2 0 4 1 1 3 0]
[0 1 3 4 7 8 9]


#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [142]:
a = np.random.random(10)
a.sort()
print(a)

[0.02261525 0.18679258 0.20195121 0.30458566 0.4716374  0.58607404
 0.70938749 0.84469491 0.87884798 0.99765653]


#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [155]:
a = np.random.random(10)
print(a)

print(a.argmax()) #argmax returns indices of the max values

a[a.argmax()] = 0 #replaces the max value by 0
print(a)

[0.22681191 0.64956595 0.86377547 0.16356516 0.86373958 0.87311727
 0.94168349 0.04087249 0.68479533 0.56559277]
6
[0.22681191 0.64956595 0.86377547 0.16356516 0.86373958 0.87311727
 0.         0.04087249 0.68479533 0.56559277]


#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [181]:
a = np.random.rand(3, 5) 
substract = a - a.mean(axis=1, keepdims=True)
print(substract)

[[ 0.13569751  0.3579242  -0.20387778 -0.14296823 -0.1467757 ]
 [-0.03271003  0.41231682 -0.39547018  0.23343257 -0.21756917]
 [-0.07736047 -0.37000904 -0.3472858   0.32497916  0.46967615]]


#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [164]:
a = np.arange(0, 10000)
print(a)

[   0    1    2 ... 9997 9998 9999]


In [165]:
np.random.shuffle(a)
print(a)

[6724 8282 3778 ... 9625 8735 9726]


In [167]:
n = 5
print(a[np.argsort(a)[-n:]]) #: means till the end

[9995 9996 9997 9998 9999]


#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [168]:
a = np.random.randint(0,10,(5,3)) #5 rows and 3 numbers in the list
print(a)

[[7 1 3]
 [3 9 0]
 [8 2 5]
 [7 2 3]
 [5 9 6]]


In [171]:
replace = np.where(a > 4, a**2, a)
print(replace)
#np.where returns the elements from 'x' or 'y' depending on the condition. If the condition (a > 4) happens the value will be replaced by 'x' (a**2), if the condition doesn't happen then the value will be replaced by 'y' (a). 

[[49  1  3]
 [ 3 81  0]
 [64  2 25]
 [49  2  3]
 [25 81 36]]
